title: Elena Lawando
logo: assets/img/headshot_round.png
description: As a detail oriented analyst, I have a passion for transforming complex data into actionable information. I am excited to utilize my skills and work as a part of a dynamic team.
#show_downloads: true
theme: jekyll-theme-minimal
